### ISSUE TITLE
Error: Proxy Error. Check console for details.

### ISSUE THREAD

**Issue by Siccity** [postwoman-io/postwoman#1027]
**Describe the bug**
Sent a basic GET request to https://www.google.com/ , got response `Error: Proxy Error. Check console for details.`

![image](https://user-images.githubusercontent.com/6402525/88535909-1abc7f00-d00b-11ea-8bcf-0e836de63c28.png)

Console does not provide much explanation

Tried disabling proxy, gives `Error: Network Error. Check console for details.` instead

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/6402525/88535657-9d910a00-d00a-11ea-96bc-961c977036d7.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version 76.0

**Comment by liyasthomas** [comment]
The endpoint `google.com` have `CORS` restrictions which why Proxy mode is mandatory for request. Turn on Proxy mode from Settings > Proxy.

It seems proxy server is down right now. Will notify when it's back online. @NBTX

**Comment by AndrewBastin** [comment]
Fixed in ebf7b32 !!!
