### ISSUE TITLE
pw.response.body is an ArrayBuffer instead of object

### ISSUE THREAD

**Issue by KoalaMoala** [postwoman-io/postwoman#1036]
**Describe the bug**

I was expecting to have an object like described here https://github.com/liyasthomas/postwoman/wiki/Post-Requests-Tests#accessing-response-data but got ArrayBuffer instead

**To Reproduce**

1. Import following collection
```json
[
  {
    "name": "My Collection",
    "folders": [], 
    "requests": [
      {   
        "url": "https://httpbin.org",
        "path": "/get",
        "method": "GET",
        "auth": "None",
        "httpUser": "", 
        "httpPassword": "", 
        "passwordFieldType": "password",
        "bearerToken": "", 
        "headers": [], 
        "params": [
          {   
            "key": "key",
            "value": ""
          }   
        ],  
        "bodyParams": [], 
        "rawParams": "", 
        "rawInput": true,
        "contentType": "", 
        "requestType": "", 
        "preRequestScript": "pw.env.set('toto', 'yolo');",
        "testScript": "pw.expect(pw.response.status).toBe(200);\npw.expect(pw.response.body).toHaveProperty('args');",
        "label": "", 
        "name": "My first request :)",
        "collection": 0
      }   
    ]   
  }
]
```
2. Run `My first request :)`
3. The second test fails with `Expected object [object ArrayBuffer] to have property args`

**Desktop (please complete the following information):**
 - MacOs Catalina, v10.15.5
 - Browser Firefox v78.0.2 && Chrome v84.0.4147.89

Thank you for your work on this project, it's very impressive !

**Comment by liyasthomas** [comment]
Thanks for reporting the issue. Looking into it.

**Comment by AndrewBastin** [comment]
This is due to the recent move to the Binary Responses System. I think we will have to introduce some helper methods to convert the body to JSON object ?

**Comment by liyasthomas** [comment]
Yes. Array buffer is served for tests. A helper function to convert response body should work.
