### ISSUE TITLE
Web Socket query string params support

### ISSUE THREAD

**Issue by Nsbx** [postwoman-io/postwoman#1056]
**Describe the bug**
If you try to connect on one ws url with some query string params the button "connect" is disabled.
But if you edit the source code to remove the "disabled" html attribute and you click on "connect" this work perfectly.

**To Reproduce**
1. Go to 'Realtime' tab
2. Type an ws url with some query string params
3. See 'connect' button is disabled

**Expected behavior**
The button shouldn't be disabled

The regex should probably be edited to accept query string params

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox developer edition
 - Version: 80.0b4

**Comment by liyasthomas** [comment]
Can you tell which URL produced disable"Connect" button? From my side, it looks okay even if there are multiple query string parameters used.

**Comment by Nsbx** [comment]
I have the problem with an url of this type (this is fake domain and fake access_token)
wss://test.test.fr/?access_token=UQUhIlQ-ZLZlveQLYYmpuUl2U6qrllDGu5LIUUcUDVYg2P6glZotUEGgAlQdx6gO1l1KZoUUKOrl4aQQgelMKQ62aoMx2Umr5hQG2lk2rvuu_UllUAE8GQGU5G4L9pPmQAp77xkZqt7IMzgTlhlHCL4O2lUUQQiclxPayP2

**Comment by liyasthomas** [comment]
The last forward slash `/` is what causing the issue.

Try this:

```
wss://test.test.fr?access_token=UQUhIlQ-ZLZlveQLYYmpuUl2U6qrllDGu5LIUUcUDVYg2P6glZotUEGgAlQdx6gO1l1KZoUUKOrl4aQQgelMKQ62aoMx2Umr5hQG2lk2rvuu_UllUAE8GQGU5G4L9pPmQAp77xkZqt7IMzgTlhlHCL4O2lUUQQiclxPayP2
```
