### ISSUE TITLE
Not able to create a collection in chrome

### ISSUE THREAD

**Issue by sameer1001** [postwoman-io/postwoman#1058]
**Describe the bug**
When I am trying to create a new collection in Chrome, it is not throwing any error, neither the collection getting created. I tried with Edge, it seems to work.

**To Reproduce**
1. Go to 'https://postwoman.io/'
2. Click on 'Collections' on the right side.
3. Click on '+ New'
4. Enter the name of the collection.
5. Click 'Save'

**Expected behavior**
The collection should be created on the right side, but I don't see any collection getting created. 

When I look at the Console, I see the attached error.

**Screenshots**
![image](https://user-images.githubusercontent.com/772341/89701198-305a6e80-d952-11ea-8f4b-2dbc0482aaf2.png)
![image](https://user-images.githubusercontent.com/772341/89701203-38b2a980-d952-11ea-8b0f-c6d14bfc5b95.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [84.0.4147.105]

**Additional context**
Seems to work in Edge, so could be an issue with Chrome latest version.

**Comment by liyasthomas** [comment]
I can't reproduce the issue here at my end. Can you produce a screenrecord?

**Comment by liyasthomas** [comment]
@AndrewBastin can you reproduce this issue at your end?

**Comment by AndrewBastin** [comment]
Nope. Can't reproduce it.

@sameer1001 if the issue is still going on for you, please clear the browser storage for Postwoman through DevTools and try again.

**Comment by liyasthomas** [comment]
Feel free to reopen if the issue persist.
