### ISSUE TITLE
Include tests in generated request link

### ISSUE THREAD

**Issue by t1m0thyj** [postwoman-io/postwoman#1061]
**Is your feature request related to a problem? Please describe.**
I have created a request that I want to share with others which includes Tests. But I can't do this without sharing the test code separately, as it isn't included in the request link.

**Describe the solution you'd like**
When I click the "Copy Request Link" button, I want all details of my current request to be included in the URL, including the Tests.

**Describe alternatives you've considered**
I could share the test code separately for others to enter, but this isn't ideal as it's an extra step for them to reproduce the request.

**Additional context**
When I click the blue button, I expect it to include any code I have entered in the red Tests section in the request link
![image](https://user-images.githubusercontent.com/22344007/89720388-96211780-d99f-11ea-9bc8-79fdd6bfbd80.png)

**Comment by liyasthomas** [comment]
Sharable request link is only for quick share among your friends.
