### ISSUE TITLE
Why not save user language in localstorage

### ISSUE THREAD

**Issue by CatchLife** [postwoman-io/postwoman#1062]
**Is your feature request related to a problem? Please describe.**
I need to select the language every time when i open postwoman

**Describe the solution you'd like**
Why not save user language in localstorage, or use user browser language as the default language

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by liyasthomas** [comment]
Are you mentioning locales available in `https://postwoman.io/cn`?
