### ISSUE TITLE
Add support for HTTP get method with request body

### ISSUE THREAD

**Issue by btpka3** [postwoman-io/postwoman#1065]
There some applications using HTTP get request with request body , such as  elasticSearch [Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/search-request-body.html)

Please discuss to support this case or not. Postwoman at now is not support GET request with HTTP request body.

reference
- stackoverflow: [HTTP GET with request body](https://stackoverflow.com/questions/978061/http-get-with-request-body) 
- stackoverflow: [Is this statement correct? HTTP GET method always has no message body](https://stackoverflow.com/a/15656853/533317)

**Comment by liyasthomas** [comment]
We're using Axios for request transactions and I guess that's not possible with Axios. see https://github.com/axios/axios/issues/2400

And as mentioned in elasticSearch [Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/search-request-body.html), we can use query parameters with `GET` request to send data as parameters. Kindly use Parameters section for that.

**Comment by AndrewBastin** [comment]
Well, we could implement it if needed. But it is not a supported behavior according to the HTTP spec. So we don't really want to support it in this app as well.

Here is the spec reference defining that [https://tools.ietf.org/html/rfc7231#page-24](https://tools.ietf.org/html/rfc7231#page-24)
