### ISSUE TITLE
It's  a little bug, this text "Create new collection" is not a property

### ISSUE THREAD

**Issue by joelcamus** [postwoman-io/postwoman#1074]
It's  a little bug, this text "Create new collection" is not a property.

![imagen](https://user-images.githubusercontent.com/8535654/90282267-5611d700-de6e-11ea-89f1-74ccd4ab6101.png)

**Comment by liyasthomas** [comment]
No it's not. Its a prompt to "Create a new Collection". Doesn't it makes sense?

**Comment by joelcamus** [comment]
This is the change

**Comment by liyasthomas** [comment]
Ahha. Got it. Will update tomorrow.

**Comment by joelcamus** [comment]
Okey, thanks

**Comment by liyasthomas** [comment]
Will update in next commit.
