### ISSUE TITLE
show div when deleted Collection, Folder, Request or Environment

### ISSUE THREAD

**Issue by joelcamus** [postwoman-io/postwoman#1080]
Add div deleted when deleted Collection, Folder, Request or Environment, you can see it in the image:
![imagen](https://user-images.githubusercontent.com/8535654/90314934-b90b7880-df17-11ea-8b03-394a6725860b.png)

This is used in history

New developments:
- [x]  Collection
- [x]  Folder
- [x]  Request
- [x]  Environment

if you want to?

**Comment by joelcamus** [comment]
Done PR #1081 :ok_hand:

**Comment by liyasthomas** [comment]
Huge thanks for all these translations @joelcamus 🎉 

Fixed in #1081
